import { Document, Image, Page, StyleSheet, Text, View, pdf } from "@react-pdf/renderer";
import {
  PDF,
  longDate,
  type MetricSection,
  type ReportData,
} from "@/lib/igloo-report";

const s = StyleSheet.create({
  page: {
    backgroundColor: PDF.white,
    color: PDF.ink,
    paddingTop: 40,
    paddingBottom: 56,
    paddingHorizontal: 44,
    fontFamily: "Helvetica",
    fontSize: 10,
  },
  wordmark: { fontFamily: "Helvetica-Bold", fontSize: 11, color: PDF.brand, letterSpacing: 2 },
  h1: { fontFamily: "Helvetica-Bold", fontSize: 20, marginTop: 6 },
  rule: { height: 2, backgroundColor: PDF.brand, marginTop: 10, marginBottom: 16, width: 64 },
  hairline: { height: 1, backgroundColor: PDF.line, marginVertical: 12 },
  h2: { fontFamily: "Helvetica-Bold", fontSize: 12, marginBottom: 8 },
  label: { fontSize: 8, color: PDF.muted, textTransform: "uppercase", letterSpacing: 0.6 },
  value: { fontSize: 11, marginTop: 2 },
  muted: { color: PDF.muted },
  metaGrid: { flexDirection: "row", flexWrap: "wrap" },
  metaCell: { width: "33.33%", marginBottom: 10 },
  cardGrid: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -5 },
  card: {
    width: "50%",
    padding: 5,
  },
  cardInner: { borderWidth: 1, borderColor: PDF.line, borderRadius: 6, padding: 10 },
  cardHead: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  swatch: { width: 10, height: 10, borderRadius: 5, marginRight: 6 },
  cardTitle: { fontFamily: "Helvetica-Bold", fontSize: 10 },
  statRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 3 },
  statKey: { color: PDF.muted, fontSize: 9 },
  statVal: { fontSize: 9, fontFamily: "Helvetica-Bold" },
  note: {
    marginTop: 4,
    backgroundColor: PDF.brandSoft,
    borderRadius: 6,
    padding: 10,
    fontSize: 9,
    color: PDF.ink,
  },
  table: { borderWidth: 1, borderColor: PDF.line, borderRadius: 4, overflow: "hidden" },
  tr: { flexDirection: "row", borderTopWidth: 1, borderTopColor: PDF.line, minHeight: 18 },
  th: { flexDirection: "row", backgroundColor: PDF.brandSoft },
  cell: { paddingVertical: 5, paddingHorizontal: 8, fontSize: 9 },
  cellHead: {
    paddingVertical: 6,
    paddingHorizontal: 8,
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: PDF.brand,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  chart: { width: "100%", marginVertical: 10 },
  sectionHead: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  sectionTitle: { fontFamily: "Helvetica-Bold", fontSize: 16 },
  statsBar: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: PDF.line,
    borderRadius: 6,
    paddingVertical: 10,
    marginBottom: 4,
  },
  statsCell: { flex: 1, paddingHorizontal: 10 },
  footer: {
    position: "absolute",
    bottom: 26,
    left: 44,
    right: 44,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: PDF.line,
    paddingTop: 6,
    fontSize: 8,
    color: PDF.muted,
  },
});

function Footer({ generated }: { generated: string }) {
  return (
    <View style={s.footer} fixed>
      <Text>Generated by Igloo on {generated}</Text>
      <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

function Header({ title, sub }: { title: string; sub?: string }) {
  return (
    <View>
      <Text style={s.wordmark}>IGLOO</Text>
      <Text style={s.h1}>{title}</Text>
      {sub ? <Text style={[s.value, s.muted]}>{sub}</Text> : null}
      <View style={s.rule} />
    </View>
  );
}

function Th({ cols }: { cols: { w: string; t: string }[] }) {
  return (
    <View style={[s.tr, s.th]} fixed>
      {cols.map((c) => (
        <Text key={c.t} style={[s.cellHead, { width: c.w }]}>
          {c.t}
        </Text>
      ))}
    </View>
  );
}

function MetricPage({
  section,
  image,
  generated,
  patient,
}: {
  section: MetricSection;
  image?: string;
  generated: string;
  patient: string;
}) {
  return (
    <Page size="A4" style={s.page} wrap>
      <View style={s.sectionHead}>
        <View style={[s.swatch, { backgroundColor: section.color, width: 14, height: 14, borderRadius: 7 }]} />
        <Text style={s.sectionTitle}>{section.label}</Text>
        <Text style={[s.statKey, { marginLeft: 8 }]}>({section.unit})</Text>
      </View>

      <View style={s.statsBar}>
        {[
          ["Average", section.average],
          ["Minimum", section.min],
          ["Maximum", section.max],
          ["Readings", String(section.count)],
        ].map(([k, v]) => (
          <View key={k} style={s.statsCell}>
            <Text style={s.label}>{k}</Text>
            <Text style={s.value}>{v}</Text>
          </View>
        ))}
      </View>

      <View style={{ marginTop: 8 }}>
        <Text style={s.label}>Reference range</Text>
        <Text style={[s.value, { fontSize: 9 }]}>{section.reference}</Text>
        {section.target ? (
          <>
            <Text style={[s.label, { marginTop: 6 }]}>Personal target range (set in app)</Text>
            <Text style={[s.value, { fontSize: 9 }]}>{section.target}</Text>
          </>
        ) : null}
      </View>

      <View style={s.hairline} />

      <Text style={s.h2}>Trend over the period</Text>
      {image ? <Image src={image} style={s.chart} /> : null}
      <Text style={[s.statKey, { marginBottom: 12 }]}>
        Light line: individual logged readings. Heavy line: rolling average.
      </Text>

      <Text style={s.h2}>All readings in this period</Text>
      <View style={s.table}>
        <Th
          cols={[
            { w: "22%", t: "Date" },
            { w: "22%", t: "Time" },
            { w: "34%", t: "Value" },
            { w: "22%", t: "Status" },
          ]}
        />
        {section.rows.map((r, i) => (
          <View key={i} style={s.tr} wrap={false}>
            <Text style={[s.cell, { width: "22%" }]}>{r.date}</Text>
            <Text style={[s.cell, { width: "22%" }]}>{r.time}</Text>
            <Text style={[s.cell, { width: "34%" }]}>{r.value}</Text>
            <Text style={[s.cell, { width: "22%", color: r.statusColor }]}>{r.status}</Text>
          </View>
        ))}
      </View>

      <Text style={[s.statKey, { marginTop: 10 }]}>Patient: {patient}</Text>
      <Footer generated={generated} />
    </Page>
  );
}

export function ReportDocument({
  data,
  images,
  combinedImage,
  patient,
}: {
  data: ReportData;
  images: Record<string, string>;
  combinedImage?: string;
  patient: { name: string; dob: string };
}) {
  const generated = longDate(data.generatedAt);
  const med = data.medication;

  return (
    <Document
      title={`Igloo Health Summary Report — ${data.range.label}`}
      author="Igloo"
      subject="Self-logged health summary"
    >
      {/* Page 1 — cover / summary */}
      <Page size="A4" style={s.page} wrap>
        <Header title="Health Summary Report" />

        <View style={s.metaGrid}>
          {[
            ["Patient", patient.name],
            ["Date of birth", patient.dob],
            ["Reporting period", data.range.label],
            ["Date generated", generated],
            ["Days in period", String(data.range.dayKeys.length)],
            ["Source", "Igloo app (self-logged)"],
          ].map(([k, v]) => (
            <View key={k} style={s.metaCell}>
              <Text style={s.label}>{k}</Text>
              <Text style={s.value}>{v}</Text>
            </View>
          ))}
        </View>

        <View style={s.hairline} />

        <Text style={s.h2}>Measurement summary</Text>
        {data.sections.length === 0 ? (
          <Text style={[s.value, s.muted]}>No measurements were logged in this period.</Text>
        ) : (
          <View style={s.cardGrid}>
            {data.sections.map((sec) => (
              <View key={sec.metric} style={s.card}>
                <View style={s.cardInner}>
                  <View style={s.cardHead}>
                    <View style={[s.swatch, { backgroundColor: sec.color }]} />
                    <Text style={s.cardTitle}>{sec.label}</Text>
                  </View>
                  <View style={s.statRow}>
                    <Text style={s.statKey}>Average</Text>
                    <Text style={s.statVal}>
                      {sec.average} {sec.unit}
                    </Text>
                  </View>
                  <View style={s.statRow}>
                    <Text style={s.statKey}>Latest</Text>
                    <Text style={s.statVal}>
                      {sec.latest} {sec.unit}
                    </Text>
                  </View>
                  <View style={s.statRow}>
                    <Text style={s.statKey}>Range (min–max)</Text>
                    <Text style={s.statVal}>
                      {sec.min}–{sec.max}
                    </Text>
                  </View>
                  <View style={s.statRow}>
                    <Text style={s.statKey}>Readings</Text>
                    <Text style={s.statVal}>{sec.count}</Text>
                  </View>
                  <Text style={[s.statKey, { marginTop: 4 }]}>Last logged {sec.latestAt}</Text>
                </View>
              </View>
            ))}
          </View>
        )}

        <View style={s.hairline} />

        <Text style={s.h2}>Medication and supplement summary</Text>
        {med.names.length === 0 ? (
          <Text style={[s.value, s.muted]}>
            No medications or supplements were logged in this period.
          </Text>
        ) : (
          <>
            <Text style={s.label}>Logged in this period</Text>
            <Text style={[s.value, { marginBottom: 8 }]}>{med.names.join(", ")}</Text>
            <Text style={s.value}>
              Logged on {med.daysLogged} of {med.totalDays} days in this period.
            </Text>
          </>
        )}

        <Text style={s.note}>
          This report reflects self-logged data from the Igloo app and is not a clinical diagnosis.
        </Text>

        <Footer generated={generated} />
      </Page>

      {/* One page per metric with data */}
      {data.sections.map((sec) => (
        <MetricPage
          key={sec.metric}
          section={sec}
          {...(images[sec.metric] ? { image: images[sec.metric] } : {})}
          generated={generated}
          patient={patient.name}
        />
      ))}

      {/* Medication log */}
      <Page size="A4" style={s.page} wrap>
        <View style={s.sectionHead}>
          <View style={[s.swatch, { backgroundColor: PDF.brand, width: 14, height: 14, borderRadius: 7 }]} />
          <Text style={s.sectionTitle}>Medication and supplement log</Text>
        </View>

        {med.rows.length === 0 ? (
          <Text style={[s.value, s.muted]}>Nothing logged in this period.</Text>
        ) : (
          <View style={s.table}>
            <Th
              cols={[
                { w: "20%", t: "Date" },
                { w: "20%", t: "Time" },
                { w: "38%", t: "Medication" },
                { w: "22%", t: "Dose" },
              ]}
            />
            {med.rows.map((r, i) => (
              <View key={i} style={s.tr} wrap={false}>
                <Text style={[s.cell, { width: "20%" }]}>{r.date}</Text>
                <Text style={[s.cell, { width: "20%" }]}>{r.time}</Text>
                <Text style={[s.cell, { width: "38%" }]}>{r.name}</Text>
                <Text style={[s.cell, { width: "22%" }]}>{r.dose}</Text>
              </View>
            ))}
          </View>
        )}

        {combinedImage ? (
          <>
            <View style={s.hairline} />
            <Text style={s.h2}>Combined view</Text>
            <Text style={[s.statKey, { marginBottom: 4 }]}>
              {data.sections[0]?.label ?? "Vitals"} trend shown with days on which medication was
              logged. Shown together for reference only; no relationship is calculated or implied.
            </Text>
            <Image src={combinedImage} style={s.chart} />
          </>
        ) : null}

        <Footer generated={generated} />
      </Page>
    </Document>
  );
}

export async function generateReportBlob(props: Parameters<typeof ReportDocument>[0]) {
  return pdf(<ReportDocument {...props} />).toBlob();
}
